#!/bin/bash

echo "🚀 StackIT Deployment Script"
echo "=============================="

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. MongoDB Atlas account and cluster"
echo "2. Railway account (for backend)"
echo "3. Vercel account (for frontend)"
echo "4. GitHub repository with your code"
echo ""

echo "🔧 Step 1: MongoDB Atlas Setup"
echo "1. Go to https://www.mongodb.com/atlas"
echo "2. Create a free account and cluster"
echo "3. Get your connection string"
echo ""

echo "🔧 Step 2: Backend Deployment (Railway)"
echo "1. Go to https://railway.app/"
echo "2. Connect your GitHub account"
echo "3. Create new project from your repo"
echo "4. Set root directory to: server"
echo "5. Add environment variables:"
echo "   - MONGO_URI: Your MongoDB connection string"
echo "   - JWT_SECRET: A strong secret key"
echo "   - NODE_ENV: production"
echo "   - FRONTEND_URL: Your frontend URL (after deployment)"
echo ""

echo "🔧 Step 3: Frontend Deployment (Vercel)"
echo "1. Go to https://vercel.com/"
echo "2. Connect your GitHub account"
echo "3. Import your repository"
echo "4. Set root directory to: frontend/StackIT_frontend"
echo "5. Add environment variable:"
echo "   - VITE_API_BASE_URL_DEPLOY: Your Railway backend URL"
echo ""

echo "🔧 Step 4: Update CORS"
echo "After getting your frontend URL, update server.js CORS settings"
echo ""

echo "✅ Deployment Complete!"
echo "Your app will be available at:"
echo "- Frontend: https://your-app.vercel.app"
echo "- Backend: https://your-app.railway.app"
echo ""

echo "🔍 Testing Checklist:"
echo "1. Test user registration"
echo "2. Test user login"
echo "3. Test question creation"
echo "4. Test answer submission"
echo "5. Test voting functionality"
echo "" 